// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.config.interceptor;

// 拦截器package
// TraceInterceptor: 用于给每一个请求添加一个唯一的traceId，方便日志追踪
// 其他拦截器: 暂未使用