// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.util;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class PasswordChecker {

    public static int checkPasswordComplexity(String password) {
        int score = 0;

        // Check for uppercase letters
        Pattern upperCase = Pattern.compile("[A-Z]");
        Matcher hasUpperCase = upperCase.matcher(password);
        if (hasUpperCase.find()) {
            score++;
        }

        // Check for lowercase letters
        Pattern lowerCase = Pattern.compile("[a-z]");
        Matcher hasLowerCase = lowerCase.matcher(password);
        if (hasLowerCase.find()) {
            score++;
        }

        // Check for digits
        Pattern digit = Pattern.compile("[0-9]");
        Matcher hasDigit = digit.matcher(password);
        if (hasDigit.find()) {
            score++;
        }

        // Check for special characters
        Pattern special = Pattern.compile("[!@#$%^&*(),.?\":{}|<>]");
        Matcher hasSpecial = special.matcher(password);
        if (hasSpecial.find()) {
            score++;
        }

        // Check for length
        if (password.length() >= 8) {
            score++;
        }

        return score;
    }

    public static void main(String[] args) {
        String password = "Password123!";
        int score = checkPasswordComplexity(password);
        System.out.println("Password score: " + score);
    }
}

