// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.entity;

import {{ cookiecutter.basePackage }}.common.entity.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 登录日志
 */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("sys_login_log")
public class LoginLog extends BaseEntity {

    private static final long serialVersionUID = 1L;

    /**
     * 登录用户名
     */
    private String loginName;

    /**
     * IP地址
     */
    private String ip;

    /**
     * 浏览器请求头
     */
    private String ua;

    /**
     * 消息
     */
    private String msg;

    /**
     * 登录是否成功（1-成功 0-失败）
     */
    private Integer isSuccess;

}
