// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.site.controller;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import {{ cookiecutter.basePackage }}.biz.auth.aspect.LogOperation;
import {{ cookiecutter.basePackage }}.biz.site.entity.Release;
import {{ cookiecutter.basePackage }}.biz.site.service.IReleaseService;
import {{ cookiecutter.basePackage }}.common.response.R;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

/**
 * 发布版本管理
 */
@RestController
@RequestMapping("/site")
@RequiredArgsConstructor
public class ReleaseController {

    final IReleaseService thisService;

    /**
     * 获取版本列表
     */
    @PreAuthorize("@ck.hasPermit('site:release:list')")
    @GetMapping("/releases")
    public R<List<Release>> list() {
        QueryWrapper<Release> wrapper = new QueryWrapper<>();
        wrapper.select("version", "description");
        wrapper.orderByDesc("create_time");
        List<Release> releases = thisService.list(wrapper);
        return R.ok(releases);
    }

    /**
     * 新增发布版本
     */
    @LogOperation(name = "新增发布版本", biz = "site")
    @PreAuthorize("@ck.hasPermit('site:release:add')")
    @PostMapping("/releases")
    public R<Release> add(@Valid @RequestBody Release entity) {
        boolean saved = thisService.save(entity);
        return saved ? R.ok(entity) : R.fail("新增发布版本失败");
    }


    /**
     * 按ID查询发布版本
     */
    @LogOperation(name = "按ID查询发布版本", biz = "site")
    @PreAuthorize("@ck.hasPermit('site:release:get')")
    @GetMapping("/releases/{id}")
    public R<Release> get(@PathVariable Integer id) {
        Release entity = thisService.getById(id);
        return entity == null ? R.fail("版本不存在") : R.ok(entity);
    }

    /**
     * 按ID更新发布版本
     */
    @LogOperation(name = "按ID更新发布版本", biz = "site")
    @PreAuthorize("@ck.hasPermit('site:release:update')")
    @PutMapping("/releases/{id}")
    public R<Void> update(@Valid @RequestBody Release entity, @PathVariable Integer id) {
        entity.setId(id);
        boolean updated = thisService.updateById(entity);
        return updated ? R.ok("更新发布版本成功") : R.fail("更新发布版本失败");
    }

    /**
     * 按ID删除发布版本
     */
    @LogOperation(name = "按ID删除发布版本", biz = "site")
    @PreAuthorize("@ck.hasPermit('site:release:delete')")
    @DeleteMapping("/releases/{id}")
    public R<Void> delete(@PathVariable Integer id) {
        boolean removed = thisService.removeById(id);
        return removed ? R.ok("删除发布版本成功") : R.fail("删除发布版本失败");
    }

}
