// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import {{ cookiecutter.basePackage }}.biz.auth.entity.App;
import {{ cookiecutter.basePackage }}.biz.auth.mapper.AppMapper;
import {{ cookiecutter.basePackage }}.biz.auth.service.IAppService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * 应用 服务实现类
 */
@Slf4j
@Service
@CacheConfig(cacheNames = "AppCache")
public class AppServiceImpl extends ServiceImpl<AppMapper, App> implements IAppService {

    /**
     * 新增应用（带缓存）
     */
    @CachePut(key = "#result.id", unless = "#result == null")
    @Override
    public App insert(App entity) {
        save(entity);
        return entity;
    }

    /**
     * 按ID查询（查询结果不为null则缓存）
     */
    @Cacheable(key = "#id", unless = "#result == null")
    @Override
    public App findById(Integer id) {
        return getById(id);
    }

    /**
     * 按ID更新（带缓存）
     */
    @CachePut(key = "#entity.id")
    @Override
    public App putById(App entity) {
        updateById(entity);
        return getById(entity.getId());
    }

    /**
     * 按ID删除（带缓存）
     */
    @CacheEvict(key = "#id")
    @Override
    public boolean deleteById(Integer id) {
        return removeById(id);
    }

}
