// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service.impl;

import {{ cookiecutter.basePackage }}.biz.auth.service.ShortMessageService;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Verification;
import {{ cookiecutter.basePackage }}.biz.sys.service.IVerificationService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

/**
 * 短信发送服务伪实现
 */
@Slf4j
@Service
public class PseudoShortMessageServiceImpl implements ShortMessageService {

    IVerificationService verificationService;

    public PseudoShortMessageServiceImpl(IVerificationService verificationService) {
        this.verificationService = verificationService;
    }

    /**
     * 发送验证码短信
     *
     * @param mobile 手机号
     * @param code   验证码
     */
    @Async
    @Override
    public void send(String mobile, String code) {
        String content = "您的验证码是：" + code + "，请在页面中提交验证码完成验证。";
        log.info(content);

        // 记录短信验证码发送记录
        Verification verification = new Verification();
        verification.setKind("mobile");
        verification.setReceiver(mobile);
        verification.setContent(content);
        verificationService.save(verification);
    }
}
