// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service.impl;

import {{ cookiecutter.basePackage }}.biz.auth.entity.Group;
import {{ cookiecutter.basePackage }}.biz.auth.entity.User;
import {{ cookiecutter.basePackage }}.biz.auth.entity.UserGroup;
import {{ cookiecutter.basePackage }}.biz.auth.mapper.UserGroupMapper;
import {{ cookiecutter.basePackage }}.biz.auth.service.IUserGroupService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.collections4.CollectionUtils;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * 用户-用户组关联 服务实现类
 */
@Slf4j
@Service
public class UserGroupServiceImpl extends ServiceImpl<UserGroupMapper, UserGroup> implements IUserGroupService {


    /**
     * 删除映射关系
     *
     * @param userId  用户ID
     * @param groupId 用户组ID
     */
    @Override
    public boolean deleteRelation(Long userId, Long groupId) {
        if (countRelation(userId, groupId) == 0) {
            return true;
        }
        return remove(buildWrapper(userId, groupId));
    }

    /**
     * 查询映射关系
     *
     * @param userId  用户ID
     * @param groupId 用户组ID
     */
    @Override
    public List<UserGroup> queryRelation(Long userId, Long groupId) {
        QueryWrapper<UserGroup> wrapper = buildWrapper(userId, groupId);
        wrapper.select("user_id, group_id");
        return list(wrapper);
    }

    /**
     * 统计映射关系
     *
     * @param userId  用户ID
     * @param groupId 用户组ID
     */
    @Override
    public Integer countRelation(Long userId, Long groupId) {
        return count(buildWrapper(userId, groupId));
    }

    /**
     * 创建映射关系
     *
     * @param userId  用户ID
     * @param groupId 用户组ID
     */
    @Override
    public boolean createRelation(Long userId, Long groupId) {
        UserGroup entity = new UserGroup(userId, groupId);
        try {
            save(entity);
        } catch (DuplicateKeyException ignored) {
            log.warn("用户组关联已存在，userId={}, groupId={}", userId, groupId);
            return true;
        }
        return true;
    }

    /**
     * 分页查询映射关系
     *
     * @param userId  用户ID
     * @param groupId 用户组ID
     */
    @Override
    public IPage<UserGroup> pageRelation(Long userId, Long groupId, IPage<UserGroup> iPage) {
        QueryWrapper<UserGroup> wrapper = buildWrapper(userId, groupId);
        wrapper.select("user_id, group_id");
        return page(iPage, wrapper);
    }

    /**
     * 更新映射关系
     *
     * @param userId   用户ID
     * @param groupIds 用户组ID列表
     */
    @Override
    public void updateRelation(Long userId, List<Long> groupIds) {
        if (CollectionUtils.isEmpty(groupIds) || userId == null || userId == 0L) {
            return;
        }

        remove(buildWrapper(userId, null));
        for (Long groupId : groupIds) {
            createRelation(userId, groupId);
        }
    }

    // 构建wrapper
    public QueryWrapper<UserGroup> buildWrapper(Long userId, Long groupId) {
        QueryWrapper<UserGroup> wrapper = new QueryWrapper<>();
        wrapper.eq(userId != null && userId != 0L, "user_id", userId);
        wrapper.eq(groupId != null && groupId != 0L, "group_id", groupId);
        return wrapper;
    }

    @Override
    public List<Group> selectGroupByUserId(Long userId) {
        return baseMapper.listGroups(userId);
    }

    @Override
    public List<User> selectUserByGroupId(Long groupId) {
        return baseMapper.listUsers(groupId);
    }
}
