// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.security;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Data
@Component
@ConfigurationProperties(prefix = "pwd")
public class PasswordProperties {

    /**
     * 密码字符集
     */
    private String chars;

    /**
     * 密码过期天数（-1代表不限制）
     */
    private Integer expireDays;


    /**
     * 初次登录后是否重置密码
     */
    private Boolean reset;

    /**
     * 最大长度
     */
    private Integer maxLength;

    /**
     * 最小长度
     */
    private Integer minLength;

    /**
     * 复杂度
     */
    private String complexity;

    /**
     * 密码历史记录数量 0代表不限制
     */
    private Integer historyCount;

    /**
     * 是否记录历史密码
     */
    private boolean enableHistory;

}
