// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.request;

import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;

@Data
public class SendCodeRequest {

    /**
     * 手机号（手机号和邮箱二选一）
     *
     * @mock 13111111111
     */
    // @NotBlank
    // @Length(min = 11, max = 11)
    private String mobile;

    /**
     * 邮箱（手机号和邮箱二选一）
     *
     * @mock admin@example.com
     */
    @NotBlank
    @Email
    private String email;

    /**
     * 获取主要账号（手机号或邮箱）
     */
    public String getPrincipal() {
        return StringUtils.isNotBlank(getMobile()) ? getMobile() : getEmail();
    }

}
