// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.request;

import lombok.Data;
import org.apache.commons.lang3.StringUtils;

@Data
public class AreaRequest {

    public static final int DEFAULT_LEVEL = 4;

    /**
     * 根节点ID
     *
     * @mock 3301
     */
    private String rootId;

    /**
     * 查询最小级别（1-国家 2-省级 3-市级 4-区县 5-镇街 6-村社）
     *
     * @mock 4
     */
    private Integer level;

    public String getRootId() {
        return StringUtils.isBlank(rootId) ? "0000" : rootId;
    }

    public Integer getLevel() {
        return level == null ? DEFAULT_LEVEL : level;
    }
}
