// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.request.group;

import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;
import java.util.List;

/**
 * 创建用户组请求
 */
@Data
public class AddGroupRequest {

    /**
     * 用户组名称
     *
     * @mock 技术部
     */
    @NotBlank(message = "用户组名称不能为空")
    private String name;

    /**
     * 父级用户组ID
     *
     * @mock 1
     */
    @Positive(message = "用户组ID必须为正整数")
    @NotNull(message = "父级用户组ID不能为空")
    private Long parentId;

    /**
     * 排序号
     *
     * @mock 1
     */
    @Positive(message = "排序号必须为正整数")
    private Integer sort;

    /**
     * 描述信息
     */
    private String description;

    /**
     * 权限ID列表
     */
    private List<Long> permissionIds;

    /**
     * 角色ID列表
     */
    private List<Long> roleIds;

}
