// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.request.group;

import lombok.Data;

import javax.validation.constraints.NotNull;

/**
 * 迁移用户组请求
 */
@Data
public class MigrateGroupRequest {

    /**
     * 新用户组ID
     */
    @NotNull(message = "新用户组ID不能为空")
    private Long parentId;

    /**
     * 当前用户组ID
     */
    @NotNull(message = "当前用户组ID不能为空")
    private Long currentId;

}
