// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.sys.area;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.apache.commons.lang3.StringUtils;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * 行政区 服务实现类
 */
@Service
@CacheConfig(cacheNames = "AreaCache")
public class AreaService extends ServiceImpl<AreaMapper, Area> {

    /**
     * 查询行政区
     *
     * @param code 行政区编码
     */
    @Cacheable(key = "#code", unless = "#result == null")
    public Area findAreaByCode(String code) {
        QueryWrapper<Area> wrapper = new QueryWrapper<>();
        wrapper.select("code, name, parent_id, level");
        wrapper.eq(StringUtils.isNotBlank(code), "code", code);
        return getOne(wrapper);
    }
}
