// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.request.password;

import lombok.Data;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

/**
 * 重置密码请求
 */
@Data
public class ResetPasswordRequest {

    /**
     * 用户ID
     *
     * @mock 10
     */
    @Positive(message = "用户ID必须为正整数")
    @NotNull(message = "用户ID不能为空")
    private Long userId;

    /**
     * 新密码（不输入则系统随机生成密码）
     *
     * @mock lHfxoPrKOaWjSqwN
     */
    @Length(min = 8, max = 32, message = "新密码长度需要8~32位")
    private String password;

}
