// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.site.leaderboard;

import lombok.Data;

@Data
public class TopResponse {

    /**
     * 成员ID
     */
    private String member;

    /**
     * 成员名称
     */
    private String name;

    /**
     * 分数
     */
    private Double score;
}
