// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.sys.log;

import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 登录日志分页查询请求
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class LoginLogRequest extends PaginationRequest {

    /**
     * 登录账号
     */
    private String account;
}
