// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.log;

import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.validation.constraints.Positive;

/**
 * 操作日志分页查询请求
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class OperateLogRequest extends PaginationRequest {

    /**
     * 操作用户ID
     */
    @Positive(message = "用户ID必须是正数")
    private Long userId;

    /**
     * 业务模块
     */
    private String biz;
}
