// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.auth.role.permission;

import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.auth.permission.Permission;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 角色权限信息 Mapper 接口
 */
@Mapper
public interface RolePermissionMapper extends BaseMapper<RolePermission> {

    /**
     * 查询角色所拥有的权限列表
     */
    List<Permission> findPermissionsByRoleId(Integer roleId);

    /**
     * 根据角色ID列表查询权限列表
     */
    List<Permission> findPermissionsByRoleIds(List<Integer> roleIds);

    /**
     * 分页查询角色拥有的权限
     */
    IPage<Permission> page(IPage<Permission> page, Integer roleId, PaginationRequest request);

}
