// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.site.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.site.entity.Feedback;

/**
 * 意见反馈 服务类
 */
public interface IFeedbackService extends IService<Feedback> {

    /**
     * 按ID查询（带缓存）
     */
    Feedback findById(Integer id);

    /**
     * 按ID更新（带缓存）
     */
    Feedback putById(Feedback feedback);

    /**
     * 按ID删除（带缓存）
     */
    void deleteById(Integer id);

}
