// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.task;

import {{ cookiecutter.basePackage }}.biz.sys.service.IDictService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;

/**
 * 应用初始化加载数据
 */
@Slf4j
@Service
public class LoadDataTask {

    @Autowired
    IDictService dictService;

    @PostConstruct
    public void load() {
        System.out.println("load data success");
    }

}
