// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sdk.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {{ cookiecutter.basePackage }}.biz.sdk.entity.OpenApi;
import org.springframework.stereotype.Repository;

/**
 * 开放接口 Mapper 接口
 */
@Repository
public interface OpenApiMapper extends BaseMapper<OpenApi> {

}
