// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.site.star;

import java.util.List;

/**
 * 收藏服务类
 */
public interface StarService {

    /**
     * 收藏，返回当前收藏数量
     *
     * @param resType 资源类型
     * @param resId   资源ID
     * @param userId  用户ID
     */
    Long star(Integer resType, Integer resId, Integer userId);

    /**
     * 取消收藏，返回当前收藏数量
     *
     * @param resType 资源类型
     * @param resId   资源ID
     * @param userId  用户ID
     */
    Long unstar(Integer resType, Integer resId, Integer userId);

    /**
     * 用户是否已收藏，当前收藏数
     *
     * @param resType 资源类型
     * @param resId   资源ID
     * @param userId  用户ID
     * @return true-已收藏，false-未收藏
     */
    boolean isStarred(Integer resType, Integer resId, Integer userId);

    /**
     * 获取用户收藏的资源ID列表
     *
     * @param resType  资源类型
     * @param userId   用户ID
     * @param pageNo   页码
     * @param pageSize 分页大小
     * @return 资源ID列表
     */
    List<StarDTO> getResIdList(Integer resType, Integer userId, Integer pageNo, Integer pageSize);

}
