// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import {{ cookiecutter.basePackage }}.biz.sys.service.CaptchaPair;
import {{ cookiecutter.basePackage }}.biz.sys.service.CaptchaService;
import {{ cookiecutter.basePackage }}.biz.sys.service.ISettingService;
import {{ cookiecutter.basePackage }}.biz.sys.service.impl.KaptchaServiceImpl;
import {{ cookiecutter.basePackage }}.biz.sys.service.impl.PatchcaServiceImpl;
import com.google.code.kaptcha.Producer;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.concurrent.TimeUnit;

@Service
public class CodeService {

    @Resource
    StringRedisTemplate stringRedisTemplate;

    @Autowired
    ISettingService settingService;

    @Autowired
    Producer captchaProducer;


    /**
     * 生成验证码
     */
    public CaptchaPair send() {
        CaptchaService captchaService;
        String kind = settingService.get("captcha.kind").getStr();
        switch (kind) {
            case "patchca":
                captchaService = new PatchcaServiceImpl(settingService);
                break;
            case "kaptcha":
            default:
                captchaService = new KaptchaServiceImpl(captchaProducer, settingService);
                break;
        }

        CaptchaPair captchaPair = captchaService.generate();
        String redisKey = settingService.get("captcha.key-prefix").getStr() + captchaPair.getCaptchaId();
        String code = captchaPair.getCode();
        Integer aliveTime = settingService.get("captcha.alive-time").getIntValue();
        stringRedisTemplate.opsForValue().set(redisKey, code, aliveTime, TimeUnit.MINUTES);
        return captchaPair;
    }

    /**
     * 校验验证码
     *
     * @param captchaId 验证码ID
     * @param code      验证码
     * @return 校验结果 true-通过、 false-不通过
     */
    public boolean verify(String code, String captchaId) {
        if (!settingService.get("captcha.on").getBool()) {
            return true;
        }

        if (StringUtils.isBlank(code) || StringUtils.isBlank(captchaId)) {
            return false;
        }

        String redisKey = settingService.get("captcha.key-prefix").getStr() + captchaId;
        Boolean hasKey = stringRedisTemplate.hasKey(redisKey);
        if (Boolean.FALSE.equals(hasKey)) {
            return false;
        }

        String captchaRedis = stringRedisTemplate.opsForValue().get(redisKey);
        if (StringUtils.isBlank(captchaRedis))
            return false;

        boolean match = captchaRedis.trim().equalsIgnoreCase(code);
        if (match) {
            stringRedisTemplate.delete(captchaId);
        }
        return match;
    }
}
