// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

public interface EmailCodeService {

    /**
     * 发送邮件验证码
     *
     * @param code 验证码
     * @param to   接收者邮箱
     */
    void sendVerificationCode(String code, String to);
}
