// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.auth.entity.GroupRole;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Role;

import java.util.List;

/**
 * 组角色关联 服务类
 */
public interface IGroupRoleService extends IService<GroupRole> {

    /**
     * 删除映射关系
     *
     * @param groupId 用户组ID
     * @param roleId  角色ID
     */
    boolean deleteRelation(Long groupId, Long roleId);

    /**
     * 查询映射关系
     *
     * @param groupId 用户组ID
     * @param roleId  角色ID
     */
    List<GroupRole> queryRelation(Long groupId, Long roleId);

    /**
     * 统计映射关系
     *
     * @param groupId 用户组ID
     * @param roleId  角色ID
     */
    Integer countRelation(Long groupId, Long roleId);

    /**
     * 创建映射关系
     *
     * @param groupId 用户组ID
     * @param roleId  角色ID
     */
    boolean createRelation(Long groupId, Long roleId);

    /**
     * 更新映射关系
     *
     * @param groupId 用户组ID
     * @param roleIds 角色ID列表
     */
    void updateRelation(Long groupId, List<Long> roleIds);

    /**
     * 根据用户组ID列表查询角色列表
     */
    List<Role> findRolesByGroupId(Long groupId);

    /**
     * 根据用户组ID列表查询角色列表
     */
    List<Role> findRolesByGroupIds(List<Long> groupIds);

}
