// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import {{ cookiecutter.basePackage }}.biz.auth.entity.PasswordHistory;
import {{ cookiecutter.basePackage }}.biz.auth.entity.User;
import {{ cookiecutter.basePackage }}.biz.auth.enums.ChangePasswordEnum;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * 密码历史表 服务类
 */
public interface IPasswordHistoryService extends IService<PasswordHistory> {

    /**
     * 按ID查询
     */
    PasswordHistory queryById(Long id);

    /**
     * 分页查询
     */
    IPage<PasswordHistory> pageQuery(IPage<PasswordHistory> page);

    /**
     * 记录密码历史
     *
     * @param user   用户
     * @param newPwd 新密码
     * @param policy 密码策略
     */
    void record(User user, String newPwd, ChangePasswordEnum policy);


}
