// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Profile;

/**
 * 用户资料 服务类
 */
public interface IProfileService extends IService<Profile> {

    /**
     * 按ID查询资料
     *
     * @param userId 用户ID
     */
    Profile findByUserId(Integer userId);


    /**
     * 更新用户资料
     *
     * @param profile 用户资料
     */
    Profile updateProfile(Profile profile);

    /**
     * 删除用户资料
     *
     * @param userId 用户ID
     */
    boolean delete(Integer userId);

}
