// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import {{ cookiecutter.basePackage }}.biz.auth.entity.User;
import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.auth.response.UserResponse;

import java.util.List;

/**
 * 用户 服务类
 */
public interface IUserService extends IService<User> {

    // 删除用户及其关联角色、用户组、权限
    boolean delete(Integer userId);

    // 禁用用户
    boolean disable(Integer userId);

    // 启用用户
    boolean enable(Integer userId);

    // 下线用户
    boolean kick(Integer userId);

    // 通过账号名查询用户
    User findByAccount(String account);

    // 查询用户拥有的角色、用户组、权限
    UserResponse attachUserInfo(User user, boolean full);

    // 更新用户关联的角色、用户组、权限
    void updateRelation(Integer userId, List<Integer> roleIds, List<Integer> groupIds, List<Integer> permissionIds);

    // 创建用户
    User create(String account, String password);

    // 获取所有有管理权限用户组成员
    List<Integer> getAllChildren(Integer userId);

    // 锁定用户并退出当前登录状态
    boolean locked(Integer userId);

    // 解锁用户
    boolean unlock(Integer userId);

    // 带缓存的ID查询
    User findById(Integer userId);
}
