// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.service;

import {{ cookiecutter.basePackage }}.biz.auth.entity.User;
import {{ cookiecutter.basePackage }}.biz.auth.request.user.AddUserRequest;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * 用户 服务类
 */
public interface IUserService extends IService<User> {

    /**
     * 添加用户
     */
    User addUser(AddUserRequest request);

    /**
     * 删除用户
     *
     * @param userId 用户ID
     */
    boolean delete(Long userId);

    /**
     * 通过ID查询用户
     *
     * @param uid 用户ID
     */
    User queryById(Long uid);

    /**
     * 修改密码
     *
     * @param userId 用户ID
     * @param newPwd 加密后的新密码
     */
    boolean changePwd(Long userId, String newPwd);

    /**
     * 通过手机号或邮箱查询用户
     *
     * @param mobile 手机号
     * @param email  邮箱号
     */
    User queryByPrincipal(String mobile, String email);

    /**
     * 禁用用户
     *
     * @param userId 用户ID
     */
    boolean disable(Long userId);

}
