// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.controller;

import com.alibaba.excel.EasyExcelFactory;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.auth.aspect.LogOperation;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Feedback;
import {{ cookiecutter.basePackage }}.biz.sys.service.IFeedbackService;
import {{ cookiecutter.basePackage }}.common.exception.DataNotFoundException;
import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import {{ cookiecutter.basePackage }}.common.response.PageVO;
import {{ cookiecutter.basePackage }}.common.response.R;
import lombok.RequiredArgsConstructor;
import {{ cookiecutter.basePackage }}.common.util.EntityUtil;
import {{ cookiecutter.basePackage }}.common.util.PageRequestUtil;
import org.springframework.http.MediaType;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.io.IOException;
import java.net.URLEncoder;

/**
 * 意见反馈管理
 */
@RestController
@RequestMapping("/sys")
@RequiredArgsConstructor
public class FeedbackController {

    final IFeedbackService thisService;

    /**
     * 意见反馈列表分页查询
     */
    @LogOperation(name = "意见反馈列表分页查询", biz = "sys")
    @PreAuthorize("@ck.hasPermit('sys:feedback:list')")
    @GetMapping("/feedbacks")
    public R<PageVO<Feedback>> list(@Valid PaginationRequest request, HttpServletResponse response) throws IOException {
        QueryWrapper<Feedback> wrapper = new QueryWrapper<>();
        wrapper.orderBy(EntityUtil.getFields(Feedback.class).contains(request.getField()),
                request.isAsc(), request.getField());
        wrapper.ge(request.getStartTime() != null, "create_time", request.getStartTime());
        wrapper.le(request.getEndTime() != null, "create_time", request.getEndTime());
        IPage<Feedback> page = PageRequestUtil.checkForMp(request);
        IPage<Feedback> list = thisService.pageQuery(page, wrapper);

        // 数据导出
        if (request.isExport()) {
            response.setContentType(MediaType.APPLICATION_OCTET_STREAM_VALUE);
            String fileName = "意见反馈";
            String baseName = URLEncoder.encode(fileName, "UTF-8").replace("\\+", "%20");
            response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + baseName + ".xlsx");
            EasyExcelFactory.write(response.getOutputStream(), Feedback.class)
                    .autoCloseStream(Boolean.TRUE).sheet("Sheet1").doWrite(list.getRecords());
            return null;
        }
        return PageRequestUtil.extractFromMp(list);
    }


    /**
     * 新增意见反馈
     */
    @PostMapping("/feedbacks")
    public R<Feedback> add(@Valid @RequestBody Feedback entity) {
        boolean success = thisService.save(entity);
        return success ? R.ok(entity) : R.fail("新增意见反馈失败");
    }


    /**
     * 按ID查询意见反馈
     */
    @LogOperation(name = "按ID查询意见反馈", biz = "sys")
    @PreAuthorize("@ck.hasPermit('sys:feedback:get')")
    @GetMapping("/feedbacks/{id}")
    public R<Feedback> get(@PathVariable Integer id) {
        Feedback entity = thisService.findById(id);
        return entity == null ? R.fail("数据不存在") : R.ok(entity);
    }

    /**
     * 按ID更新意见反馈
     */
    @LogOperation(name = "按ID更新意见反馈", biz = "sys")
    @PreAuthorize("@ck.hasPermit('sys:feedback:update')")
    @PutMapping("/feedbacks/{id}")
    public R<Void> update(@PathVariable Integer id, @Valid @RequestBody Feedback entity) {
        entity.setId(id);
        checkId(id);
        boolean success = thisService.updateById(entity);
        return success ? R.ok("更新意见反馈成功") : R.fail("更新意见反馈失败");
    }

    /**
     * 按ID删除意见反馈
     */
    @LogOperation(name = "按ID删除意见反馈", biz = "sys")
    @PreAuthorize("@ck.hasPermit('sys:feedback:delete')")
    @DeleteMapping("/feedbacks/{id}")
    public R<Void> delete(@PathVariable Integer id) {
        boolean success = thisService.removeById(id);
        return success ? R.ok("删除意见反馈成功") : R.fail("删除意见反馈失败");
    }

    public void checkId(Integer id) {
        Feedback entity = thisService.getById(id);
        if (entity == null) {
            throw new DataNotFoundException("数据不存在: " + id);
        }
    }
}
