// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.controller;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import {{ cookiecutter.basePackage }}.biz.sys.entity.FriendlyUrl;
import {{ cookiecutter.basePackage }}.biz.sys.service.IFriendlyUrlService;
import {{ cookiecutter.basePackage }}.common.response.R;
import lombok.RequiredArgsConstructor;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;

/**
 * 友情链接管理
 */
@RestController
@RequiredArgsConstructor
@RequestMapping("/sys/friendly")
public class FriendlyUrlController {

    private static final int ENABLE = 1;

    final IFriendlyUrlService thisService;

    /**
     * 获取友链列表
     */
    @GetMapping("/urls")
    @Cacheable(cacheNames = "UrlCache", unless = "#result == null")
    public R<List<FriendlyUrl>> list() {
        QueryWrapper<FriendlyUrl> wrapper = new QueryWrapper<>();
        wrapper.select("id", "content", "url");
        wrapper.eq("status", ENABLE);
        wrapper.orderByAsc("sort");
        List<FriendlyUrl> urls = thisService.list(wrapper);
        return R.ok(urls);
    }

    /**
     * 添加友链
     */
    @CacheEvict(cacheNames = "UrlCache", allEntries = true)
    @PreAuthorize("@ck.hasPermit('sys:friendly:add')")
    @PostMapping("/urls")
    public R<FriendlyUrl> add(@Valid @RequestBody FriendlyUrl entity) {
        boolean saved = thisService.save(entity);
        return saved ? R.ok(entity) : R.fail("新增失败");
    }

    /**
     * 删除友链
     *
     * @param id 友链ID
     */
    @CacheEvict(cacheNames = "UrlCache", allEntries = true)
    @PreAuthorize("@ck.hasPermit('sys:friendly:delete')")
    @DeleteMapping("/urls/{id}")
    public R<FriendlyUrl> delete(@PathVariable("id") Long id) {
        if (entity == null) return R.fail("友链不存在");
        boolean removed = thisService.removeById(id);
        return removed ? R.ok("删除友链成功") : R.fail("删除友链失败");
    }

    /**
     * 更新友链
     *
     * @param id     友链ID
     * @param entity 友链实体
     * @return 友链实体
     */
    @CacheEvict(cacheNames = "UrlCache", allEntries = true)
    @PreAuthorize("@ck.hasPermit('sys:friendly:update')")
    @PutMapping("/urls/{id}")
    public R<FriendlyUrl> update(@PathVariable Long id, @Valid @RequestBody FriendlyUrl entity) {
        entity.setId(id);
        FriendlyUrl result = thisService.getById(id);
        if (result == null) return R.fail("友链不存在");
        boolean updated = thisService.updateById(entity);
        return updated ? R.ok(entity) : R.fail("更新友链失败");
    }

}
