// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.controller;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Info;
import {{ cookiecutter.basePackage }}.biz.sys.service.IInfoService;
import {{ cookiecutter.basePackage }}.common.response.ApiResponse;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 系统信息管理
 */
@RestController
@RequestMapping("/sys")
@CacheConfig(cacheNames = "infoCache")
public class InfoController {

    IInfoService thisService;

    public InfoController(IInfoService thisService) {
        this.thisService = thisService;
    }

    /**
     * 获取系统信息列表
     */
    @Cacheable
    @GetMapping("/infos")
    public ApiResponse<Map<String, String>> list() {
        QueryWrapper<Info> wrapper = new QueryWrapper<>();
        wrapper.select("param_key", "param_value");
        List<Info> params = thisService.list(wrapper);
        Map<String, String> map = new HashMap<>();
        params.forEach(info -> map.put(info.getParamKey(), info.getParamValue()));
        return new ApiResponse<>(map);
    }

    /**
     * 新增系统信息
     */
    @PreAuthorize("@ck.hasPermit('sys:info:add')")
    @PostMapping("/infos")
    public ApiResponse<Info> add(@Valid @RequestBody Info entity) {
        boolean success = thisService.save(entity);
        if (success) {
            return new ApiResponse<>(entity);
        }
        return new ApiResponse<>("新增失败", false);
    }

    /**
     * 按ID更新系统信息
     */
    @PreAuthorize("@ck.hasPermit('sys:info:update')")
    @PutMapping("/infos/{id}")
    public ApiResponse<Object> update(@PathVariable Long id, @Valid @RequestBody Info entity) {
        entity.setId(id);
        boolean success = thisService.updateById(entity);
        if (success) {
            return new ApiResponse<>("更新成功");
        }
        return new ApiResponse<>("更新失败", false);
    }


    /**
     * 按ID删除系统信息
     */
    @PreAuthorize("@ck.hasPermit('sys:info:delete')")
    @DeleteMapping("/infos/{id}")
    public ApiResponse<Object> delete(@PathVariable Long id) {
        boolean success = thisService.removeById(id);
        if (success) {
            return new ApiResponse<>("删除成功");
        }
        return new ApiResponse<>("删除失败", false);
    }

}
