// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.controller;

import org.springframework.web.bind.annotation.RequestMapping;

@RequestMapping("/sys/jvm")
public class JvmController {

    // 获取jvm信息

}
