// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.request.login;

import lombok.Data;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;

// 邮箱+邮箱验证码登录
@Data
public class LoginByEmailRequest {

    /**
     * 邮箱
     */
    @Email
    @NotBlank
    private String email;

    /**
     * 邮箱验证码
     */
    @NotBlank
    private String code;
}
