// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import {{ cookiecutter.basePackage }}.common.entity.LiteEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

/**
 * 用户组权限
 */
@Data
@TableName("auth_group_permission")
@EqualsAndHashCode(callSuper = true)
public class GroupPermission extends LiteEntity {

    private static final long serialVersionUID = 1L;

    /**
     * 用户组ID
     */
    private Integer groupId;

    /**
     * 权限ID
     */
    @Positive(message = "权限ID必须为正数")
    @NotNull(message = "权限ID不能为空")
    private Integer permissionId;

    public GroupPermission(Integer groupId, Integer permissionId) {
        this.groupId = groupId;
        this.permissionId = permissionId;
    }

}
