// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import {{ cookiecutter.basePackage }}.common.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotBlank;

/**
 * 安全问题
 */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("auth_question")
public class Question extends BaseEntity {

    private static final long serialVersionUID = 1L;

    /**
     * 安全问题
     */
    @Length(max = 64, message = "安全问题长度不能超过64个字符")
    @NotBlank(message = "安全问题不能为空")
    private String question;

}
