// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.response;


import {{ cookiecutter.basePackage }}.biz.auth.entity.Profile;
import lombok.Data;

@Data
public class LoginResponse {

    /**
     * 用户信息
     */
    private Profile profile;

    /**
     * 用户名
     *
     * @mock admin
     */
    private String username;

    /**
     * 令牌
     */
    private String token;

    /**
     * 是否管理员
     */
    private boolean admin;
}
