// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.common.request;

/**
 * 基础请求
 */
public class BaseRequest {

    /**
     * 请求毫秒时间戳
     *
     * @mock 1644541518652
     */
    private Long ts;

    /**
     * 请求体签名
     */
    private String sign;

    /**
     * 随机数
     */
    private String nonce;

    public Long getTs() {
        return ts;
    }

    public void setTs(Long ts) {
        this.ts = ts;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    public String getNonce() {
        return nonce;
    }

    public void setNonce(String nonce) {
        this.nonce = nonce;
    }
}
