// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.common.request;

import lombok.Data;
import org.hibernate.validator.constraints.Range;

import {{ cookiecutter.namespace }}.validation.constraints.NotNull;

/**
 * 主键ID请求
 */
@Data
public class IdRequest {

    /**
     * 主键ID
     */
    @Range(min = 1, message = "ID必须为正整数")
    @NotNull(message = "ID不能为空")
    private Integer id;

}
