// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.common.request;

import lombok.Data;
import lombok.EqualsAndHashCode;
import org.apache.commons.lang3.StringUtils;

// 带排序的分页请求
@EqualsAndHashCode(callSuper = true)
@Data
public class OrderPageRequest extends PaginationRequest {

    /**
     * 排序方式 asc/desc
     */
    private String order;

    /**
     * 排序字段
     */
    private String sort;


    public Boolean getOrder() {
        return StringUtils.isBlank(order) || order.equalsIgnoreCase("asc");
    }

    public String getSort() {
        return StringUtils.isNotBlank(sort) ? sort : "id";
    }
}
