// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.config.security.mobile;

import {{ cookiecutter.basePackage }}.biz.auth.login.CodeLoginRequest;
import {{ cookiecutter.basePackage }}.biz.auth.mfa.AccountUtil;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpMethod;
import org.springframework.security.authentication.AuthenticationServiceException;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter;
import org.springframework.security.web.util.matcher.AntPathRequestMatcher;

import {{ cookiecutter.namespace }}.servlet.http.HttpServletRequest;
import {{ cookiecutter.namespace }}.servlet.http.HttpServletResponse;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

/**
 * 验证码登录过滤器
 */
@Slf4j
public class SmsCodeAuthenticationFilter extends AbstractAuthenticationProcessingFilter {

    /**
     * 登录请求体json 账号key
     */
    public static final String ACCOUNT = "account";

    public SmsCodeAuthenticationFilter() {
        // 处理的验证码登录请求处理url
        super(new AntPathRequestMatcher("/auth/login/code", HttpMethod.POST.name()));
    }

    @Override
    public Authentication attemptAuthentication(HttpServletRequest req, HttpServletResponse res) throws AuthenticationException, IOException {
        if (!req.getMethod().equals(HttpMethod.POST.name())) {
            throw new AuthenticationServiceException("不支持的Http方法: {}" + req.getMethod());
        }

        // 从请求body中获取手机号或邮箱和验证码
        CodeLoginRequest loginRequest = obtainCodeLoginRequest(req);
        String account = loginRequest.getAccount();
        String code = loginRequest.getCode();

        if (account == null) {
            account = "";
        }

        if (!(AccountUtil.isEmail(account) || AccountUtil.isMobile(account))) {
            throw new AuthenticationServiceException("账号格式错误, 请输入正确的手机号或邮箱");
        }

        if (code == null) {
            code = "";
        }

        account = account.trim();
        req.setAttribute(ACCOUNT, account);
        // 创建SmsCodeAuthenticationToken(未认证)
        SmsCodeAuthenticationToken authRequest = new SmsCodeAuthenticationToken(account, code);

        // 设置用户信息
        setDetails(req, authRequest);
        // 返回Authentication实例
        return this.getAuthenticationManager().authenticate(authRequest);
    }


    protected CodeLoginRequest obtainCodeLoginRequest(HttpServletRequest req) throws JsonProcessingException {
        StringBuilder stringBuilder = new StringBuilder();
        try (InputStream inputStream = req.getInputStream();
             BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream))) {
            char[] charBuffer = new char[128];
            int bytesRead;
            while ((bytesRead = bufferedReader.read(charBuffer)) > 0) {
                stringBuilder.append(charBuffer, 0, bytesRead);
            }

        } catch (IOException e) {
            log.error("读取请求body失败", e);
        }

        String requestBody = stringBuilder.toString();
        ObjectMapper objectMapper = new ObjectMapper();
        return objectMapper.readValue(requestBody, CodeLoginRequest.class);
    }

    protected void setDetails(HttpServletRequest request, SmsCodeAuthenticationToken authRequest) {
        authRequest.setDetails(authenticationDetailsSource.buildDetails(request));
    }
}
