// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }};

import {{ cookiecutter.basePackage }}.biz.auth.service.IPermissionService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class TestPermission {

    @Autowired
    IPermissionService permissionService;


    @Test
    void t1() {
        Integer userId = 10;
        // System.out.println(permissionService.getAllPermissions(userId));
        System.out.println(permissionService.getSecurityPermissions(userId));
    }
}
