// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }};

import {{ cookiecutter.basePackage }}.common.util.RateUtil;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * 百分比计算工具类单元测试
 */
class TestRate {

    @Test
    void test01() {
        Assertions.assertEquals(RateUtil.cal(1, 1), "100%");
        Assertions.assertEquals(RateUtil.cal(4, 20), "20%");
    }
}
