// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }};

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class {{ cookiecutter.app_name }}ApplicationTests {

}
