// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Dict;

import java.util.List;

/**
 * 字典数据表 服务类
 */
public interface IDictService extends IService<Dict> {

    /**
     * 查询指定字典
     *
     * @param dictType  字典类型
     * @param dictValue 字典值
     */
    Dict queryDict(String dictType, String dictValue);

    /**
     * 按dict_type查询所有
     *
     * @param dictType 字典类型
     */
    List<Dict> listAllDicts(String dictType);
}
