// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Dict;

import java.util.List;

/**
 * 字典数据表 服务类
 */
public interface IDictService extends IService<Dict> {

    /**
     * 按字典类型查询所有字典
     *
     * @param dictType 字典类型
     */
    List<Dict> listDictsByType(String dictType);

    /**
     * 新增字典条目（带缓存）
     */
    Dict insert(Dict entity);

    /**
     * 删除字典条目
     */
    boolean deleteDict(String dictType, Integer id);

    /**
     * 更新字典条目
     */
    boolean updateDict(Dict entity);

    /**
     * 删除字典类型
     */
    boolean deleteByDictType(String dictType);
}
