// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import {{ cookiecutter.basePackage }}.biz.sys.entity.File;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * 文件 服务类
 */
public interface IFileService extends IService<File> {

    /**
     * 按ID查询
     */
    File findById(Long id);

}
