// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import {{ cookiecutter.basePackage }}.biz.sys.entity.Info;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * 系统信息 服务类
 */
public interface IInfoService extends IService<Info> {

}
