// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import com.baomidou.mybatisplus.extension.service.IService;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Setting;
import {{ cookiecutter.basePackage }}.biz.sys.response.Item;

/**
 * 系统设置 服务类
 */
public interface ISettingService extends IService<Setting> {

    /**
     * 按ID查询
     */
    Setting queryById(Long id);

    /**
     * 按名称查询设置项
     *
     * @param label 选项名称
     */
    Item get(String label);

    /**
     * 更新设置项
     *
     * @param label 选项名称
     * @param value 选项值
     */
    Item update(String label, String value);
}
