// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

import {{ cookiecutter.basePackage }}.biz.sys.entity.Verification;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * 验证码发送记录 服务类
 */
public interface IVerificationService extends IService<Verification> {

    /**
     * 按ID查询
     */
    Verification findById(Long id);

}
