// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service;

public interface VerifyService {

    /**
     * 校验验证码
     *
     * @param captchaId 验证码ID
     * @param captcha   验证码
     * @return 校验结果
     */
    boolean verify(String captcha, String captchaId);
}
