// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.site.feedback;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * 意见反馈 服务实现类
 */
@Slf4j
@Service
public class FeedbackService extends ServiceImpl<FeedbackMapper, Feedback>  {

    /**
     * 按ID查询（带缓存）
     */
    @Cacheable(cacheNames = "FeedbackCache", key = "#id", unless = "#result == null")
    public Feedback findById(Integer id) {
        return getById(id);
    }

    /**
     * 按ID更新（带缓存）
     */
    @CachePut(cacheNames = "FeedbackCache", key = "#feedback.id")
    public Feedback putById(Feedback feedback) {
        updateById(feedback);
        return getById(feedback.getId());
    }

    /**
     * 按ID删除（带缓存）
     */
    @CacheEvict(cacheNames = "FeedbackCache", key = "#id")
    public void deleteById(Integer id) {
        removeById(id);
    }

}
