// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.controller;

import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import {{ cookiecutter.basePackage }}.biz.auth.entity.User;
import {{ cookiecutter.basePackage }}.biz.auth.request.user.BindingRequest;
import {{ cookiecutter.basePackage }}.biz.auth.service.IUserService;
import {{ cookiecutter.basePackage }}.biz.auth.service.ValidateService;
import {{ cookiecutter.basePackage }}.biz.auth.util.AccountUtil;
import {{ cookiecutter.basePackage }}.common.controller.AuthBaseController;
import {{ cookiecutter.basePackage }}.common.response.ApiResponse;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;

/**
 * 绑定认证方式
 */
@RequestMapping("/auth")
@RestController
public class BindingController extends AuthBaseController {
    IUserService userService;

    ValidateService validateService;

    public BindingController(IUserService userService, ValidateService validateService) {
        this.userService = userService;
        this.validateService = validateService;
    }

    /**
     * 绑定手机号或邮箱
     */
    @PostMapping("/binding")
    public ApiResponse<Boolean> binding(@Valid @RequestBody BindingRequest request) {
        String account = request.getAccount();
        if (userService.queryByAccount(account) != null) {
            return new ApiResponse<>("该账号已绑定其他用户", false);
        }

        // 获取redis中验证码, 校验是否正确
        String key = "code:" + account;
        if (!validateService.validate(key, request.getCode())) {
            return new ApiResponse<>("验证码错误", false);
        }

        // 更新用户信息
        UpdateWrapper<User> wrapper = new UpdateWrapper<>();
        wrapper.set(AccountUtil.isMobile(account), "mobile", account);
        wrapper.set(AccountUtil.isEmail(account), "email", account);
        wrapper.eq("id", getUserId());
        boolean success = userService.update(wrapper);
        if (!success) {
            return new ApiResponse<>("绑定失败", false);
        }

        return new ApiResponse<>("绑定成功");
    }
}
