// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.controller;

import cn.hutool.crypto.digest.DigestUtil;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.auth.aspect.LogOperation;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Answer;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Question;
import {{ cookiecutter.basePackage }}.biz.auth.mapper.QuestionMapper;
import {{ cookiecutter.basePackage }}.biz.auth.request.qa.AddAnswerRequest;
import {{ cookiecutter.basePackage }}.biz.auth.request.qa.UpdateAnswerRequest;
import {{ cookiecutter.basePackage }}.biz.auth.service.IAnswerService;
import {{ cookiecutter.basePackage }}.biz.auth.service.IQuestionService;
import {{ cookiecutter.basePackage }}.biz.auth.service.ValidateService;
import {{ cookiecutter.basePackage }}.common.controller.AuthBaseController;
import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import {{ cookiecutter.basePackage }}.common.response.PageVO;
import {{ cookiecutter.basePackage }}.common.response.R;
import {{ cookiecutter.basePackage }}.common.util.PageRequestUtil;
import lombok.RequiredArgsConstructor;
import org.apache.commons.collections4.CollectionUtils;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;

/**
 * 安全问题管理
 */
@RestController
@RequiredArgsConstructor
@RequestMapping("/auth")
public class QuestionController extends AuthBaseController {

    final IQuestionService thisService;
    final QuestionMapper thisMapper;
    final IAnswerService answerService;
    final ValidateService validateService;
    final StringRedisTemplate stringRedisTemplate;
    private final Random random = new Random();

    /**
     * 安全问题分页查询
     */
    @LogOperation(name = "安全问题分页查询", biz = "auth")
    @PreAuthorize("@ck.hasPermit('auth:question:list')")
    @GetMapping("/questions")
    public R<PageVO<Question>> page(@Valid PaginationRequest request) {
        QueryWrapper<Question> wrapper = new QueryWrapper<>();
        wrapper.select("id", "question");
        wrapper.like(request.getKeyword() != null, "question", request.getKeyword());
        IPage<Question> page = PageRequestUtil.checkForMp(request);
        IPage<Question> list = thisService.page(page, wrapper);
        return PageRequestUtil.extractFromMp(list);
    }


    /**
     * 查询所有安全问题
     */
    @PreAuthorize("@ck.hasPermit('auth:question:list')")
    @GetMapping("/questions/list")
    public R<List<Question>> list() {
        QueryWrapper<Question> wrapper = new QueryWrapper<>();
        wrapper.select("id", "question");
        return R.ok(thisService.list(wrapper));
    }


    /**
     * 新增安全问题
     */
    @LogOperation(name = "新增安全问题", biz = "auth")
    @PreAuthorize("@ck.hasPermit('auth:question:add')")
    @PostMapping("/questions")
    public R<Question> add(@Valid @RequestBody Question entity) {
        boolean success = thisService.save(entity);
        return success ? R.ok(entity) : R.fail("新增安全问题失败");
    }


    /**
     * 按ID删除安全问题
     */
    @LogOperation(name = "按ID删除安全问题", biz = "auth")
    @PreAuthorize("@ck.hasPermit('auth:question:delete')")
    @DeleteMapping("/questions/{id}")
    public R<Void> delete(@PathVariable Long id) {
        if (answerService.isAlreadyUsed(id)) {
            return R.fail("该安全问题已经被使用，无法删除");
        }

        boolean success = thisService.removeById(id);
        return success ? R.ok("删除安全问题成功") : R.fail("删除安全问题失败");
    }

    /**
     * 随机查询用户设置的安全问题
     */
    @LogOperation(name = "随机查询用户设置的安全问题", biz = "auth")
    @GetMapping("/questions/random")
    public R<Question> get() {
        List<Question> questions = thisMapper.findQuestionsByUserId(getUserId());
        if (CollectionUtils.isEmpty(questions)) {
            return R.fail("请先设置安全问题");
        }

        // 随机查询出一个问题
        Question question = questions.get(random.nextInt(questions.size()));
        stringRedisTemplate.opsForValue().set("question:" + getUserId(), String.valueOf(question.getId()));
        return R.ok(question);
    }

    /**
     * 用户设置安全问题
     */
    @LogOperation(name = "用户设置安全问题", biz = "auth")
    @PostMapping("/answers")
    public R<Void> add(@Valid @RequestBody AddAnswerRequest request) {
        List<Question> questions = thisMapper.findQuestionsByUserId(getUserId());
        if (CollectionUtils.isNotEmpty(questions)) {
            return R.fail("用户已经设置过安全问题");
        }

        boolean success = saveAnswers(request, getUserId());
        return success ? R.ok("成功设置安全问题") : R.fail("新增安全问题失败");
    }

    /**
     * 用户修改安全问题（需先校验验证码）
     */
    @LogOperation(name = "用户修改安全问题", biz = "auth")
    @PutMapping("/answers")
    public R<Void> update(@Valid @RequestBody UpdateAnswerRequest request) {
        String key = "code:" + getUserId();
        if (!validateService.validate(key, request.getCode())) return R.fail("验证码错误");

        QueryWrapper<Answer> wrapper = new QueryWrapper<>();
        wrapper.eq("user_id", getUserId());
        boolean removed = answerService.remove(wrapper);
        boolean saved = saveAnswers(request, getUserId());
        return (removed && saved) ? R.ok("成功修改密保问题") : R.fail("修改密保问题失败");
    }


    // 保存用户安全问题答案
    private boolean saveAnswers(AddAnswerRequest request, Long userId) {
        List<Answer> answers = request.getAnswers().stream().map(ans -> {
            Answer answer = new Answer();
            answer.setUserId(userId);
            answer.setQuestionId(ans.getQuestionId());
            answer.setSecret(DigestUtil.md5Hex(ans.getAnswer().trim()));  // md5加密，防止数据库泄露
            return answer;
        }).collect(Collectors.toList());
        return answerService.saveBatch(answers);
    }

}
