// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.site;

// 该包为网站、App、小程序通用功能模块，该模块下包含以下功能：
// 1. checkin：       用户签到
// 2. feedback：      意见反馈
// 3. follow：        用户关注
// 4. friendly：      友情链接管理
// 5. info：          系统信息管理
// 6. like：          点赞管理
// 7. realname：      实名认证
// 8. release：       系统版本
// 9. star：          收藏管理
// 10. pay：           支付管理
// 11. miniprogram：     微信小程序管理