// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.common.constraint.file;

import javax.validation.Constraint;
import java.lang.annotation.*;

/**
 * 上传文件校验注解
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Constraint(validatedBy = UploadFileValidator.class)
public @interface UploadFile {

    /**
     * 支持上传的扩展名
     */
    String[] allowedExtensions() default {};

    /**
     * 文件最大大小 默认10Mb
     */
    int maxSize() default 1024 * 1024 * 10;

    /**
     * 文件最小大小 默认0
     */
    int minSize() default 0;

    String message() default "文件格式不支持";

    /**
     * @return the groups the constraint belongs to
     */
    Class<?>[] groups() default {};

    /**
     * @return the payload associated to the constraint
     */
    Class<?>[] payload() default {};

}
