// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service.impl;

import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.sys.entity.File;
import {{ cookiecutter.basePackage }}.biz.sys.mapper.FileMapper;
import {{ cookiecutter.basePackage }}.biz.sys.service.IFileService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * 文件 服务实现类
 */
@Slf4j
@Service
public class FileServiceImpl extends ServiceImpl<FileMapper, File> implements IFileService {

    /**
     * 按ID查询
     */
    @Cacheable(cacheNames = "FileCache", key = "#id", unless = "#result == null")
    @Override
    public File queryById(Long id) {
        return getById(id);
    }

    /**
     * 分页查询
     */
    @Cacheable(cacheNames = "FileCache", key = "#p.getCurrent()+#p.getSize()")
    @Override
    public IPage<File> pageQuery(IPage<File> p) {
        return page(p);
    }

}
