// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service.impl;

import cn.hutool.core.util.IdUtil;
import {{ cookiecutter.basePackage }}.biz.sys.service.CaptchaPair;
import {{ cookiecutter.basePackage }}.biz.sys.service.CaptchaService;
import {{ cookiecutter.basePackage }}.biz.sys.service.ISettingService;
import com.google.code.kaptcha.Producer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Slf4j
@RequiredArgsConstructor
public class KaptchaServiceImpl implements CaptchaService {

    final ISettingService setting;
    final Producer captchaProducer;

    @Override
    public CaptchaPair generate() {
        String captchaId = IdUtil.simpleUUID();
        String capText = captchaProducer.createText();
        BufferedImage bi = captchaProducer.createImage(capText);
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        try {
            ImageIO.write(bi, setting.get("captcha.format").getStr(), byteArrayOutputStream);
        } catch (IOException e) {
            log.error("kaptcha error: ", e);
        }
        return new CaptchaPair(byteArrayOutputStream, capText, captchaId);
    }
}
