// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service.impl;

import {{ cookiecutter.basePackage }}.biz.sys.service.FileStoreService;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.FileOutputStream;

@Service
public class LocalFileStoreServiceImpl implements FileStoreService {

    public static final String PROTOCOL = "file://";

    public static final String LOCAL_FILE_STORE = "/tmp";

    /**
     * 上传文件
     *
     * @param file       文件
     * @param objectName 文件名
     * @return 文件地址
     */
    @Override
    public String upload(MultipartFile file, String objectName) {
        // 将文件保存到本地
        try {
            String path = LOCAL_FILE_STORE + "/" + objectName;
            // File file1 = new File(path);
            new File(path).getParentFile().mkdirs();
            FileOutputStream fs = new FileOutputStream(path);
            fs.write(file.getBytes());
            fs.close();
            // file.transferTo(new File(path));
            return PROTOCOL + path;
        } catch (Exception ignored) {
        }
        return null;
    }

    /**
     * 删除文件
     *
     * @param objectName 文件名
     */
    @Override
    public boolean delete(String objectName) {
        File file = new File(LOCAL_FILE_STORE, objectName);
        return file.delete();
    }
}
