// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.service.impl;

import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Verification;
import {{ cookiecutter.basePackage }}.biz.sys.mapper.VerificationMapper;
import {{ cookiecutter.basePackage }}.biz.sys.service.IVerificationService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import lombok.extern.slf4j.Slf4j;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/**
 * 验证码发送记录 服务实现类
 */
@Slf4j
@Service
public class VerificationServiceImpl extends ServiceImpl<VerificationMapper, Verification> implements IVerificationService {

    /**
     * 按ID查询
     */
    @Cacheable(cacheNames = "VerificationCache", key = "#id")
    @Override
    public Verification queryById(Long id) {
        return getById(id);
    }

    /**
     * 分页查询
     */
    @Cacheable(cacheNames = "VerificationCache", key = "#p.getCurrent()+#p.getSize()")
    @Override
    public IPage<Verification> pageQuery(IPage<Verification> p) {
        return page(p);
    }

}
