// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.common.constant;

/**
 * 分页常量
 */
public class PageConst {

    private PageConst() {
    }

    /**
     * 默认页码
     */
    public static final int DEFAULT_CURRENT = 1;

    /**
     * 分页大小
     */
    public static final int DEFAULT_PAGE_SIZE = 10;
}
