// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.sys.counter;

import com.baomidou.mybatisplus.annotation.TableName;
import {{ cookiecutter.basePackage }}.common.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * 计数器
 */
@Data
@TableName("sys_counter")
@EqualsAndHashCode(callSuper = true)
public class Counter extends BaseEntity {

    private static final long serialVersionUID = 1L;

    /**
     * 键
     */
    private String biz;

    /**
     * 计数值
     */
    private Long number;

    public Counter(String biz, Long number) {
        this.biz = biz;
        this.number = number;
    }

    public Counter() {
    }

}
