// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import {{ cookiecutter.basePackage }}.biz.auth.entity.GroupPermission;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Permission;
import {{ cookiecutter.basePackage }}.common.request.PaginationRequest;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * 用户组权限 Mapper 接口
 */
@Repository
public interface GroupPermissionMapper extends BaseMapper<GroupPermission> {

    // 查询用户组拥有的权限代码列表
    List<Permission> findPermissionsByGroupId(Long groupId);

    // 查询用户组拥有的权限代码列表
    List<Permission> findPermissionsByGroupIds(List<Long> groupIds);

    /**
     * 分页查询用户组下的权限
     */
    IPage<Permission> page(IPage<Permission> page, Long groupId, PaginationRequest request);

}
