// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.mapper;

import {{ cookiecutter.basePackage }}.biz.auth.entity.Permission;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {{ cookiecutter.basePackage }}.biz.auth.entity.RolePermission;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * 角色权限信息 Mapper 接口
 */
@Repository
public interface RolePermissionMapper extends BaseMapper<RolePermission> {

    // 查询角色所拥有的权限列表
    List<Permission> getPermissionByRoleId(long roleId);

}
