// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {{ cookiecutter.basePackage }}.biz.auth.entity.Role;
import {{ cookiecutter.basePackage }}.biz.auth.entity.UserRole;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * 用户和角色关联表 Mapper 接口
 */
@Repository
public interface UserRoleMapper extends BaseMapper<UserRole> {

    // 根据用户ID 查询该用户所拥有的角色信息
    List<Role> selectRoleByUserId(Long userId);
}
