// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.common.request.auth;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

import {{ cookiecutter.basePackage }}.common.request.BaseRequest;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;


@Data
@EqualsAndHashCode(callSuper = false)
public class UpdateAuthRequest extends BaseRequest {

    /**
     * 权限、角色、用户组名称
     *
     * @mock 更新项目
     */
    private String name;

    /**
     * 描述信息
     */
    private String description;

    /**
     * 权限ID列表
     */
    private List<@Positive @NotNull Integer> permissionIds;

    /**
     * 角色ID列表
     */
    private List<@Positive @NotNull Integer> roleIds;
}
