// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.site.service.impl;

import {{ cookiecutter.basePackage }}.biz.site.entity.Info;
import {{ cookiecutter.basePackage }}.biz.site.mapper.InfoMapper;
import {{ cookiecutter.basePackage }}.biz.site.service.IInfoService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * 系统信息 服务实现类
 */
@Service
public class InfoServiceImpl extends ServiceImpl<InfoMapper, Info> implements IInfoService {

}
