// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.acl;

import com.baomidou.mybatisplus.annotation.TableName;
import {{ cookiecutter.basePackage }}.common.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;

/**
 * IP黑名单
 */
@Data
@TableName("sys_blacklist")
@EqualsAndHashCode(callSuper = true)
public class Blacklist extends BaseEntity {

    private static final long serialVersionUID = 1L;

    /**
     * IP地址
     */
    private String ip;

    /**
     * 截止时间
     */
    private LocalDateTime endTime;

    /**
     * 备注
     */
    private String remark;

}
