// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.config.mybatis;

import cn.hutool.core.util.StrUtil;
import {{ cookiecutter.basePackage }}.common.constant.ProjectConst;
import com.baomidou.mybatisplus.core.handlers.MetaObjectHandler;
import {{ cookiecutter.basePackage }}.config.security.LoginUser;
import org.apache.ibatis.reflection.MetaObject;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component
public class MybatisPlusMetaObjectHandler implements MetaObjectHandler {

    private static final String CREATE_FIELD = StrUtil.toCamelCase(ProjectConst.CREATE_FIELD);
    private static final String UPDATE_FIELD = StrUtil.toCamelCase(ProjectConst.UPDATE_FIELD);

    // mybatis plus 插入时填充策略
    @Override
    public void insertFill(MetaObject metaObject) {
        this.setFieldValByName(CREATE_FIELD, LocalDateTime.now(), metaObject);
        this.setFieldValByName(UPDATE_FIELD, LocalDateTime.now(), metaObject);
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null){
            LoginUser loginUser = (LoginUser) authentication.getPrincipal();
            this.setFieldValByName("createBy", loginUser.getUser().getId(), metaObject);
            this.setFieldValByName("updateBy", loginUser.getUser().getId(), metaObject);
        }
    }

    // mybatis plus 更新时填充策略
    @Override
    public void updateFill(MetaObject metaObject) {
        this.setFieldValByName(UPDATE_FIELD, LocalDateTime.now(), metaObject);
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null){
            LoginUser loginUser = (LoginUser) authentication.getPrincipal();
            this.setFieldValByName("updateBy", loginUser.getUser().getId(), metaObject);
        }
    }
}
