// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// And git commit hash is {% gitcommit %}.

package {{ cookiecutter.basePackage }}.biz.sys.dict;

import lombok.Data;

import {{ cookiecutter.namespace }}.validation.constraints.NotBlank;
import {{ cookiecutter.namespace }}.validation.constraints.Pattern;


/**
 * 批量查询字典请求
 */
@Data
public class MultiDictTypeRequest {

    /**
     * 多种字典类型使用逗号分隔
     *
     * @mock gender,education
     */
    @Pattern(regexp = "^[a-zA-Z,_]+$", message = "字典类型只能包含字母、逗号和下划线")
    @NotBlank(message = "字典类型不能为空")
    private String types;
}
