// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.group.role;

import com.baomidou.mybatisplus.annotation.TableName;
import {{ cookiecutter.basePackage }}.common.entity.LiteEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Positive;

/**
 * 用户组角色关联
 */
@Data
@TableName("auth_group_role")
@EqualsAndHashCode(callSuper = true)
public class GroupRole extends LiteEntity {

    private static final long serialVersionUID = 1L;

    /**
     * 用户组ID
     */
    private Integer groupId;

    /**
     * 角色ID
     */
    @Positive(message = "角色ID必须为正数")
    @NotNull(message = "角色ID不能为空")
    private Integer roleId;

    public GroupRole(Integer groupId, Integer roleId) {
        this.groupId = groupId;
        this.roleId = roleId;
    }
}
