// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.sys.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import {{ cookiecutter.basePackage }}.biz.sys.entity.Counter;
import org.springframework.stereotype.Repository;

/**
 * 计数器 Mapper 接口
 */
@Repository
public interface CounterMapper extends BaseMapper<Counter> {

}
