// This project was generated by {{ cookiecutter.author_name }} at {% now 'local', '%Y-%m-%d %X' %}.
// The version of generator is v{{ cookiecutter._version }}.

package {{ cookiecutter.basePackage }}.biz.auth.enums;

/**
 * 账号类型枚举
 */
public enum AccountEnum {

    USERNAME("username"),
    MOBILE("mobile"),
    EMAIL("email"),

    /**
     * 非法字符串
     */
    ILLEGAL("illegal");

    private final String kind;

    AccountEnum(String kind) {
        this.kind = kind;
    }

    public String getKind() {
        return kind;
    }
}
